---
- name: Create an EC2 instance
  hosts: localhost
  become: yes
  gather_facts: no
  vars: 
    aws_region: "us-east-1"
    ec2_instance_type: "t2.micro"
    ec2_key_name: "AnsibleKey" 
    ec2_security_group: "sg-0c113fb628c8748ee"
    ec2_ami: "ami-04a81a99f5ec58529"

  tasks:
    - name: Create an EC2 instance
      community.aws.ec2_instance:
        name: "MyEC2Instance"
        region: "us-east-1"
        instance_type: "t2.micro"
        key_name: "AnsibleKey"
        security_groups: "sg-0c113fb628c8748ee"
        image_id: "ami-04a81a99f5ec58529"
        wait: yes
        count: 1
      register: ec2
      environments:
        aws_access_key_id: AKIA3FLD2760EDPGRM3M
        aws_secret_access_key: M/CBVa0ZrQ6zFGH8gfb5HVWSHXCqspatx131/Zd1
            

    - name: Print instance information
      debug: 
        var: ec2.instances