---
- name: Install and start Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update APT package manager repositories and cache
      apt: 
        update_cache: yes
    
    - name: Install Nginx
      apt: 
        name: nginx
        state: present

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes


        An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.NoCredentialsError: Unable to locate credentials
fatal: [localhost]: FAILED! => {"boto3_version": "1.34.152", "botocore_version": "1.34.152", "changed": false, "msg": "Could not describe default VPC: Unable to locate credentials"}
