---
- name: Install and start Nginx
  hosts: all
  become: yes

  tasks:
    - name: Update APT package manager repositories and cache
      apt: 
        update_cache: yes
    
    - name: Install Nginx
      apt: 
        name: nginx
        state: present

    - name: Start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes





samprita@samprita-VirtualBox:~/AnsibleProject$ aws configure
AWS Access Key ID [****************RM3M]: AKIA3FLD2760EDPGRM3M
AWS Secret Access Key [****************/Zd1]: M/CBVa0ZrQ6zFGH8gfb5HVWSHXCqspatx131/Zd1
Default region name [ldmj]: us-east-1
Default output format [kdj]: 
samprita@samprita-VirtualBox:~/AnsibleProject$ ansible-playbook create-ec2.yml -vvv
ansible-playbook [core 2.16.3]
  config file = /home/samprita/AnsibleProject/ansible.cfg
  configured module search path = ['/home/samprita/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/samprita/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /home/samprita/AnsibleProject/ansible.cfg as config file
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
yaml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
ini declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Skipping due to inventory source not existing or not being readable by the current user
toml declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'
redirecting (type: modules) community.aws.ec2_instance to amazon.aws.ec2_instance
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: create-ec2.yml ***********************************************************************************************
1 plays in create-ec2.yml

PLAY [Create an EC2 instance] ******************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
task path: /home/samprita/AnsibleProject/create-ec2.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: samprita
<127.0.0.1> EXEC /bin/sh -c 'echo ~samprita && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/samprita/.ansible/tmp `"&& mkdir "` echo /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702 `" && echo ansible-tmp-1722590572.25595-7513-37319900822702="` echo /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/setup.py
<127.0.0.1> PUT /home/samprita/.ansible/tmp/ansible-local-7509rd6y_x2t/tmpmc64y879 TO /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702/AnsiballZ_setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702/ /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702/AnsiballZ_setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n  -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-dcqcksdymwchumlbearsmwpahgajrbhx ; /usr/bin/python3 /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702/AnsiballZ_setup.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/samprita/.ansible/tmp/ansible-tmp-1722590572.25595-7513-37319900822702/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "ansible_facts": {},
    "changed": false,
    "failed_modules": {
        "ansible.legacy.setup": {
            "failed": true,
            "module_stderr": "sudo: a password is required\n",
            "module_stdout": "",
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
            "rc": 1
        }
    },
    "msg": "The following modules failed to execute: ansible.legacy.setup\n"
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

samprita@samprita-VirtualBox:~/AnsibleProject$ 



